version: '3'

services:
  ocr_proj_dev:
    container_name: ocr_proj_dev
    build:
      context: .
    working_dir: /extension
    command: cextrun -d
    volumes: 
      - .:/extension
    env_file:
      - .ocr_proj_dev.env

  ocr_proj_bash:
    container_name: ocr_proj_bash
    build:
      context: .
    working_dir: /extension
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    env_file:
      - .ocr_proj_dev.env

  ocr_proj_test:
    container_name: ocr_proj_test
    build:
      context: .
    working_dir: /extension
    command: extension-test
    volumes:
      - .:/extension
    env_file:
      - .ocr_proj_dev.env
